### ISSUE TITLE
How-to for dummies

### ISSUE THREAD

**Issue by nigelhorne** [mikkelee/genealogytree-mkgraph#2]
You may find this of use.

On Debian I ran:
sudo apt-get apt-get install texlive-full
cd src
git clone https://github.com/T-F-S/genealogytree
cd genealogytree
sudo find doc tex/ | cpio -pvdul /usr/local/share/texmf/
cd ..
git clone https://github.com/mikkelee/genealogytree-mkgraph.git
cd genealogytree-mkgraph.git
 ./mkgraph.pl -a 4 -x I1 -f /home/njh/gedcoms/Horne\ Family\ Tree\ -\ 2018\ 10\ 12\ 16-18.ged > in.tex
[ edit the in.tex using https://tex.stackexchange.com/questions/296402/genealogytree-ancestor-approach to insert the parent statement in a wrapper ]
texi2pdf in.tex
[ look at in.pdf in amazement ]

**Comment by nigelhorne** [comment]
My Dad's date of death is missing from the output of mkgraph.pl.

[out.pdf](https://github.com/mikkelee/genealogytree-mkgraph/files/2526805/out.pdf)

**Comment by nigelhorne** [comment]
My Dad's date of death is missing from the output of mkgraph.pl.

**Comment by mikkelee** [comment]
The script puts the marriage information on the edges between the families. They can be formatted using `label options` in the genealogytree setup, see section _8.4 Edge Labels_ in the genealogytree documentation. Below are the relevant parts of my own settings:

```latex
\gtrset{
	database format=full no marriage, % don't display marriage on person nodes, is irrelevant here as script doesn't put marriage info there anyway
	label options={
		fill=white,
		node font=\tiny,
		inner sep=0.5mm,
		draw=green!30!black
	},
}
```

I should probably provide an option for putting the marriage information on the spouse, as is used in some of the "official" `database format`s.

**Comment by nigelhorne** [comment]
This patch now prints my Dad's death correctly.  You'll need to do the same thing for birth etc.:

```
*** Omkgraph.pl	Tue Oct 30 07:17:33 2018
--- mkgraph.pl	Tue Oct 30 07:15:22 2018
***************
*** 240,246 ****
  		print &processEvent("baptism", $indi->christening, $indent);
  	}
  	#TODO floruit?
! 	if (defined $indi->death) {
  		print &processEvent("death", $indi->death, $indent);
  	}
  	if (defined $indi->burial) {
--- 240,248 ----
  		print &processEvent("baptism", $indi->christening, $indent);
  	}
  	#TODO floruit?
! 	if(my $death = $indi->record('death')) {
! 		print &processEvent("death", $death, $indent);
! 	} elsif (defined $indi->death) {
  		print &processEvent("death", $indi->death, $indent);
  	}
  	if (defined $indi->burial) {
```

**Comment by mikkelee** [comment]
Thanks, I've incorporated your suggestions and made various other improvements :)

**Comment by nigelhorne** [comment]
That's much better - thank you - all the data are appearing.  Somehow all of the boxes are red now.

<img width="1105" alt="screen shot 2018-10-30 at 9 39 31 am" src="https://user-images.githubusercontent.com/739072/47722051-e47c8080-dc27-11e8-9daa-e25e116b5124.png">

**Comment by mikkelee** [comment]
Appears that it didn't recognise genders properly. I've pushed an update.

**Comment by nigelhorne** [comment]
Works - closing.
